version: '3.8'

services:
  app:
    build:
      context: .
    container_name: microProfesor-container
    ports:
      - "8082:8082"
    depends_on:
      - db

  db:
    image: mysql:lates
    container_name: some-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mateo
      MYSQL_DATABASE: profesordb
      MYSQL_USER: root
      MYSQL_PASSWORD: mateo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: